version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    labels:
    - area/testing
    - area/github-actions
    - kind/enhancement
