# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/master/.golangci.yaml as a
# reference.
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - godot
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - ireturn
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    - wastedassign

linters-settings:
  cyclop:
    skip-tests: true

  goheader:
    template: |-
      SPDX-License-Identifier: Apache-2.0
      Copyright Authors of Cilium
  gosimple:
    go: "1.18"
  govet:
    enable-all: true
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"
  unused:
    go: "1.18"
