# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a
# reference.
version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    goheader:
      template: |-
        SPDX-License-Identifier: Apache-2.0
        Copyright Authors of Cilium
    govet:
      enable-all: true
    perfsprint:
      strconcat: false
    sloglint:
      no-mixed-args: true
      static-msg: true
      no-global: "all"
      key-naming-case: kebab # be consistent with key names
      forbidden-keys: # let's no use reserved log keys
        - level
        - msg
        - source
        - time
  exclusions:
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable (default is 50)
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable (default is 3)
  max-same-issues: 0
  fix: true # fix found issues (if it's supported by the linter).
formatters:
  enable:
    - gofmt
    - goimports
